### ISSUE TITLE
Windows keep going background after drag and drop images to editor

### ISSUE THREAD

**Issue by diimdeep** [uranusjr/macdown#250] opened 2015-01-27 11:25 UTC

**Comment by uranusjr** [comment] 2015-02-01 10:14
I seem to unable to reproduce this on my machine. Could you be more specific on what happened (maybe record a short video or something)? Also it would be nice if you could provide some information about your computer (MBP/MBA/iMac, Retina or not, Yosemite/Mavericks/Snow Lion, etc.).

**Comment by diimdeep** [comment] 2015-02-01 10:31
Can't reproduce either, maybe some bug in cocoa or interference from other
software.

**Comment by uranusjr** [comment] 2015-02-01 11:59
I guess I’ll close this for now then. Feel free to reopen this if it happens (with consistency) again.

**Closed by uranusjr** 2015-02-01 11:59 UTC
Labels: awaiting feedback
